version: '3.8'

services:
  db:
    env_file:
      - ./backend/.env.test
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

  backend:
    env_file:
      - ./backend/.env.test

  test:
    build: ./backend
    image: pms_backend:latest
    container_name: pms-test
    command: ["pytest", "-v"]
    env_file:
      - ./backend/.env.test
    volumes:
      - ./backend:/app
    networks:
      - pms_network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
