services:
  backend:
    environment:
      - DATABASE_TYPE=sqlite
      - CACHE_TYPE=disk
    ports:
      - "8000:8000"

  frontend:
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
