services:
  test-sqlite:
    build: ./backend
    container_name: pms-test-sqlite
    command: sh -c "pip install -r requirements-dev.in && pytest -v"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_TYPE=sqlite
      - CACHE_TYPE=disk
      - TESTING=True
    networks:
      - pms_network
