networks:
  pms_network:
    driver: bridge

volumes:
  postgres_data:
  postgres_data_test:

services:
  db:
    image: postgres:13
    container_name: pms-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pms_network

  redis:
    image: redis:alpine
    container_name: pms-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pms_network

  backend:
    build: ./backend
    image: pms_backend:latest
    container_name: pms-backend
    restart: unless-stopped
    command: /app/entrypoint.sh
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - PYTHONPATH=/app
    networks:
      - pms_network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/auth/status"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s

  frontend:
    build: ./frontend
    image: pms_frontend:latest
    container_name: pms-frontend
    restart: unless-stopped
    networks:
      - pms_network
    depends_on:
      - backend
