services:
  test:
    build: ./backend
    container_name: pms-test
    command: ["pytest", "-v"]
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_TYPE=sqlite
      - TESTING=True
    networks:
      - pms_network
    depends_on:
      redis:
        condition: service_healthy
