services:
  db:
    env_file:
      - ./backend/.env.test
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

  test:
    build: ./backend
    container_name: pms-test
    command: ["pytest", "-v"]
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_TYPE=postgres
      - TESTING=True
    networks:
      - pms_network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
