"""Add source to import sessions

Revision ID: 1c3a7e6d8b5f
Revises: a2b4c6d8e0f1
Create Date: 2025-08-12 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3a7e6d8b5f'
down_revision = 'a2b4c6d8e0f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_sessions', sa.Column('source', sa.String(), nullable=False, server_default='Unknown'))
    op.alter_column('import_sessions', 'source', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_sessions', 'source')
    # ### end Alembic commands ###
