"""Add parsed_file_path to import_sessions

Revision ID: 469bd61f2d16
Revises: f44c5a861184
Create Date: 2025-08-01 10:54:49.981266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469bd61f2d16'
down_revision: Union[str, None] = 'f44c5a861184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_sessions', sa.Column('parsed_file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_sessions', 'parsed_file_path')
    # ### end Alembic commands ###