"""Add exchange and isin to assets table

Revision ID: 5e0d9fccdd7e
Revises: 1f45affeb138
Create Date: 2025-07-24 03:14:01.360399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e0d9fccdd7e'
down_revision: Union[str, None] = '1f45affeb138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('exchange', sa.String(), server_default='N/A', nullable=False))
    op.add_column('assets', sa.Column('isin', sa.String(), nullable=True))
    op.create_index(op.f('ix_assets_isin'), 'assets', ['isin'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_isin'), table_name='assets')
    op.drop_column('assets', 'isin')
    op.drop_column('assets', 'exchange')
    # ### end Alembic commands ###