"""Add PPF tracking models and interest rates

Revision ID: 60049686f011
Revises: 2fc13ed78a51
Create Date: 2025-09-09 04:10:46.255362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.custom_types import GUID
from sqlalchemy.engine import reflection

# revision identifiers, used by Alembic.
revision: str = '60049686f011'
down_revision: Union[str, None] = '2fc13ed78a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_interest_rates',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('scheme_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_name', 'start_date', name='uq_historical_interest_rate_scheme_date')
    )
    op.create_index(op.f('ix_historical_interest_rates_scheme_name'), 'historical_interest_rates', ['scheme_name'], unique=False)
    op.add_column('assets', sa.Column('account_number', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('opening_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    A defensive downgrade that checks for table existence before dropping columns.
    This prevents errors when downgrading a tangled migration history.
    """
    conn = op.get_bind()
    inspector = reflection.Inspector.from_engine(conn)
    tables = inspector.get_table_names()

    if 'assets' in tables:
        op.drop_column('assets', 'opening_date')
        op.drop_column('assets', 'account_number')
    if 'historical_interest_rates' in tables:
        op.drop_index(op.f('ix_historical_interest_rates_scheme_name'), table_name='historical_interest_rates')
        op.drop_table('historical_interest_rates')