"""Add details to transactions

Revision ID: 6475d96e6255
Revises: bbecc17535a9
Create Date: 2025-11-26 10:46:51.331015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6475d96e6255'
down_revision: Union[str, None] = 'bbecc17535a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_asset_name_type_currency'), 'assets', type_='unique')
    op.drop_index(op.f('ix_bonds_asset_id'), table_name='bonds')
    op.create_unique_constraint(None, 'bonds', ['asset_id'])
    op.alter_column('historical_interest_rates', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('historical_interest_rates', 'rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_historical_interest_rate_scheme_date'), 'historical_interest_rates', type_='unique')
    op.alter_column('parsed_transactions', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.add_column('transactions', sa.Column('details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'details')
    op.alter_column('parsed_transactions', 'data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_historical_interest_rate_scheme_date'), 'historical_interest_rates', ['scheme_name', 'start_date'], postgresql_nulls_not_distinct=False)
    op.alter_column('historical_interest_rates', 'rate',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('historical_interest_rates', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_constraint(None, 'bonds', type_='unique')
    op.create_index(op.f('ix_bonds_asset_id'), 'bonds', ['asset_id'], unique=True)
    op.create_unique_constraint(op.f('uq_asset_name_type_currency'), 'assets', ['name', 'asset_type', 'currency'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###