"""add ppf and interest rate models

Revision ID: 719dbe1deafc
Revises: f44c5a861184
Create Date: 2025-09-08 01:16:53.982269

"""
from alembic import op
import sqlalchemy as sa
from app.db.custom_types import GUID


# revision identifiers, used by Alembic.
revision = '719dbe1deafc'
down_revision = 'f44c5a861184'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_interest_rates',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('scheme_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('assets', sa.Column('account_number', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('opening_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'opening_date')
    op.drop_column('assets', 'account_number')
    op.drop_table('historical_interest_rates')
    # ### end Alembic commands ###
