"""Add error_message to import_sessions

Revision ID: 79fbc0246a96
Revises: d8b5e3d7f2c1
Create Date: 2025-08-05 07:12:32.662051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79fbc0246a96'
down_revision: Union[str, None] = 'd8b5e3d7f2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['import_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_assets_id', table_name='assets')
    op.add_column('import_sessions', sa.Column('error_message', sa.String(), nullable=True))
    op.drop_index('ix_portfolios_id', table_name='portfolios')
    op.drop_index('ix_transactions_id', table_name='transactions')
    op.drop_index('ix_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_transactions_id', 'transactions', ['id'], unique=False)
    op.create_index('ix_portfolios_id', 'portfolios', ['id'], unique=False)
    op.drop_column('import_sessions', 'error_message')
    op.create_index('ix_assets_id', 'assets', ['id'], unique=False)
    op.drop_table('parsed_transactions')
    # ### end Alembic commands ###