"""add goals and goal_links tables

Revision ID: 8ae91cbe7aa4
Revises: b5a5e3d7f2c1
Create Date: 2025-08-24 17:20:47.178662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = '8ae91cbe7aa4'
down_revision: Union[str, None] = 'b5a5e3d7f2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', app.db.custom_types.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_amount', sa.Numeric(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('user_id', app.db.custom_types.GUID(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False, server_default=sa.text('now()')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal_links',
    sa.Column('id', app.db.custom_types.GUID(), nullable=False),
    sa.Column('goal_id', app.db.custom_types.GUID(), nullable=False),
    sa.Column('portfolio_id', app.db.custom_types.GUID(), nullable=True),
    sa.Column('asset_id', app.db.custom_types.GUID(), nullable=True),
    sa.Column('user_id', app.db.custom_types.GUID(), nullable=False),
    sa.CheckConstraint('(portfolio_id IS NOT NULL AND asset_id IS NULL) OR (portfolio_id IS NULL AND asset_id IS NOT NULL)', name='check_goal_link_target'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal_links')
    op.drop_table('goals')
    # ### end Alembic commands ###