"""Add bond model and related changes

Revision ID: a1b2c3d4e5f6
Revises: 60049686f011
Create Date: 2025-09-18 10:32:00.123456

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "a1b2c3d4e5f6"
down_revision = "60049686f011"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bonds",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("asset_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("bond_type", sa.String(), nullable=False),
        sa.Column("face_value", sa.Numeric(), nullable=True),
        sa.Column("coupon_rate", sa.Numeric(), nullable=True),
        sa.Column("maturity_date", sa.Date(), nullable=False),
        sa.Column("isin", sa.String(), nullable=True),
        sa.Column("payment_frequency", sa.String(), nullable=True),
        sa.Column("first_payment_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bonds_asset_id"), "bonds", ["asset_id"], unique=True)
    op.create_index(op.f("ix_bonds_isin"), "bonds", ["isin"], unique=False)
    op.create_unique_constraint("uq_asset_name_type_currency", "assets", ["name", "asset_type", "currency"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_asset_name_type_currency", "assets", type_="unique")
    op.drop_index(op.f("ix_bonds_isin"), table_name="bonds")
    op.drop_index(op.f("ix_bonds_asset_id"), table_name="bonds")
    op.drop_table("bonds")
    # ### end Alembic commands ###