"""Add is_reinvested to transactions

Revision ID: bbecc17535a9
Revises: a1b2c3d4e5f6
Create Date: 2025-10-07 04:52:28.650946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbecc17535a9'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_reinvested', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    op.alter_column('transactions', 'is_reinvested', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_reinvested')
    # ### end Alembic commands ###