"""add_watchlist_and_watchlist_item_tables

Revision ID: dff8e00ff3d0
Revises: b5a5e3d7f2c1
Create Date: 2025-08-24 17:17:44.779352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.custom_types import GUID


# revision identifiers, used by Alembic.
revision: str = 'dff8e00ff3d0'
down_revision: Union[str, None] = 'b5a5e3d7f2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlists',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_items',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('watchlist_id', GUID(), nullable=False),
    sa.Column('asset_id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'asset_id', name='uq_watchlist_asset')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_items')
    op.drop_table('watchlists')
    # ### end Alembic commands ###