from enum import Enum


class BondType(str, Enum):
    CORPORATE = "CORPORATE"
    GOVERNMENT = "GOVERNMENT"
    SGB = "SGB"
    TBILL = "TBILL"


class PaymentFrequency(str, Enum):
    ANNUALLY = "ANNUALLY"
    SEMI_ANNUALLY = "SEMI_ANNUALLY"
    QUARTERLY = "QUARTERLY"
    MONTHLY = "MONTHLY"
    ON_MATURITY = "ON_MATURITY"


class TransactionType(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    DIVIDEND = "DIVIDEND"
    SPLIT = "SPLIT"
    BONUS = "BONUS"
    CONTRIBUTION = "CONTRIBUTION"
    INTEREST_CREDIT = "INTEREST_CREDIT"
    COUPON = "COUPON"
    ESPP_PURCHASE = "ESPP_PURCHASE"
    RSU_VEST = "RSU_VEST"
    MERGER = "MERGER"
    DEMERGER = "DEMERGER"
    RENAME = "RENAME"
